name: Deploy Inventory Management

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        npm install
        npm install -g aws-cdk

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Build Lambda Functions
      run: |
        cd lambda/data-entry && npm install && npx tsc
        cd ../query && npm install && npx tsc

    - name: Deploy CDK Stack
      run: cdk deploy --require-approval never
